version: 2
jobs:
    test_frontend:
        docker:
            - image: circleci/node
    steps:
        - checkout
        - run:
          name: yarn install
          working_directory: api
          command: yarn install
workflows:
    version: 2
    run_test:
        jobs:
            - test_frontend